---
- name: Install RPM packages
  dnf:
      name: ['git', 'vim', 'poetry', 'python3-flask', 'python3-pip', 'python3-cryptography', 'freeipa-server']
      state: present

- name: install freeipa server
  shell: ipa-server-install -a adminPassw0rd! --hostname=ipa.example.test -r EXAMPLE.TEST -p adminPassw0rd! -n example.test -U

- name: get freeipa-fas
  git:
    repo: https://github.com/fedora-infra/freeipa-fas.git
    dest: /tmp/freeipa-fas

- name: install freeipa-fas
  shell: ./install.sh
  args:
    chdir: /tmp/freeipa-fas/